remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: The (SecOps) Feed
description: The Feed is a curated Operational Threat Intelligence list of articles of interest for SOC / DFIR / CTI and Threat Hunting Teams.
author: Ruslan Rustchev
show_downloads: true