remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
minima:
  skin: dark
title: The (SecOps) Feed
description: The Feed is a curated Operational Threat Intelligence list of articles of interest for SOC / DFIR / CTI and Threat Hunting Teams.
author: Ruslan Rustchev
layouts_dir: _layouts
header-pages: 
  - The-Feed
  